### ISSUE TITLE
Event linking from search

### ISSUE THREAD

**Issue by nikidinsey** [XronosSchedulingLtd/scheduler#10]
When searching for an event, the resulting list of events can't be clicked on to see the event detail.

You can click on the date of the event, but unless you have the right concerns switched on you are unable to always see the event.

Can you please add an event detail link to the search results, thanks!

Niki

**Comment by jhwinters** [comment]
That's on my list of minor enhancements for this month.

**Comment by jhwinters** [comment]
Implemented in v1.8.1
