### ISSUE TITLE
Event organiser info when querying event

### ISSUE THREAD

**Issue by ghost** [XronosSchedulingLtd/scheduler#11]
Can information about the event organiser be sent within the response query when querying an event with the following a similar command:

`curl -K curl.opt https://schedulerdemo.xronos.uk/api/events/3`

**Comment by jhwinters** [comment]
Good idea.  This query currently gives back no more information than an event listing.  As it's asking for information about one specific event there are several more pieces of info it could provide.

**Comment by jhwinters** [comment]
Added in release 1.8.3
